enum ApiErrorCode {
  verificationCodeInvalid('VERIFICATION_CODE_INVALID'),
  unauthenticated('UNAUTHENTICATED'),
  invalidCredentials('INVALID_CREDENTIALS'),
  invalidRefreshToken('INVALID_REFRESH_TOKEN'),
  invalidVerificationToken('INVALID_VERIFICATION_TOKEN'),
  forbidden('FORBIDDEN'),
  adminRequired('ADMIN_REQUIRED'),
  participationNotOwned('PARTICIPATION_NOT_OWNED'),
  notFound('NOT_FOUND'),
  householdNotFound('HOUSEHOLD_NOT_FOUND'),
  memberNotFound('MEMBER_NOT_FOUND'),
  verificationNotFound('VERIFICATION_NOT_FOUND'),
  invitationNotFound('INVITATION_NOT_FOUND'),
  taskNotFound('TASK_NOT_FOUND'),
  routineNotFound('ROUTINE_NOT_FOUND'),
  swapRequestNotFound('SWAP_REQUEST_NOT_FOUND'),
  commentNotFound('COMMENT_NOT_FOUND'),
  suggestionNotFound('SUGGESTION_NOT_FOUND'),
  phoneAlreadyRegistered('PHONE_ALREADY_REGISTERED'),
  alreadyMember('ALREADY_MEMBER'),
  lastAdminMustTransfer('LAST_ADMIN_MUST_TRANSFER'),
  templatesAlreadyApplied('TEMPLATES_ALREADY_APPLIED'),
  taskCompletedLocked('TASK_COMPLETED_LOCKED'),
  participationNotAvailable('PARTICIPATION_NOT_AVAILABLE'),
  assigneeRestricted('ASSIGNEE_RESTRICTED'),
  similarTasksFound('SIMILAR_TASKS_FOUND'),
  swapRequestNotPending('SWAP_REQUEST_NOT_PENDING'),
  suggestionNotPending('SUGGESTION_NOT_PENDING'),
  capacityNotConfigured('CAPACITY_NOT_CONFIGURED'),
  idempotencyKeyReused('IDEMPOTENCY_KEY_REUSED'),
  conflict('CONFLICT'),
  verificationExpired('VERIFICATION_EXPIRED'),
  invitationExpired('INVITATION_EXPIRED'),
  versionConflict('VERSION_CONFLICT'),
  attachmentTooLarge('ATTACHMENT_TOO_LARGE'),
  unsupportedMediaType('UNSUPPORTED_MEDIA_TYPE'),
  validationError('VALIDATION_ERROR'),
  capacitySumInvalid('CAPACITY_SUM_INVALID'),
  unplannedTaskOutOfRange('UNPLANNED_TASK_OUT_OF_RANGE'),
  accountLocked('ACCOUNT_LOCKED'),
  rateLimited('RATE_LIMITED'),
  verificationAttemptsExceeded('VERIFICATION_ATTEMPTS_EXCEEDED'),
  verificationResendTooSoon('VERIFICATION_RESEND_TOO_SOON'),
  internalError('INTERNAL_ERROR'),
  smsDeliveryFailed('SMS_DELIVERY_FAILED'),
  serviceUnavailable('SERVICE_UNAVAILABLE'),
  unknown('UNKNOWN');

  const ApiErrorCode(this.value);
  final String value;

  static ApiErrorCode fromValue(Object? value) =>
      values.firstWhere((code) => code.value == value, orElse: () => unknown);
}
